title: "DeGroot_GithubConsumerComplaints"
author: "Lia DeGroot"
date: "5/6/2022"
output: 
  flexdashboard::flex_dashboard:
  verticla_layout: scroll

---

```{r setup, include=FALSE}

`complaints (1)` <- readRDS("~/Desktop/github_lia/DEGROOT_GITHUBHOMEWOKR/complaints (1).rds")

library(tidyverse)
library(janitor)
library(readxl)
library(scales)
library(lubridate)
library(ggthemes)
library(esquisse)
library(dplyr)
library(ggplot2)
library(flexdashboard)
```
```{r}
```


```{r}

complaints_bydate <- `complaints (1)` %>% 
  count(date_received)
```


-------------------------------------
    
### Chart 1 
    
```{r}

ggplot(complaints_bydate, aes(x = date_received, y = n)) + 
  geom_line()
```
 
-------------------------------------
   
### Chart 2 


```{r}

complaints_byproduct <- `complaints (1)` %>% 
  count(product)
ggplot(complaints_byproduct, aes(x = product, y = n)) +
  geom_col() +
  coord_flip() 
 

```   

-------------------------------------

### Chart 3 
    
```{r}
complaints_bystate <- `complaints (1)` %>% 
  count(state)

ggplot(complaints_bystate, aes(x = state, y = n)) +
  geom_col() +
  coord_flip() 
 
```